networks:
  reverse_proxy:
    external: true


volumes:
    grafana_data: {}


services:
  qryn:
    image: qxip/qryn:latest
    ports:
      - "3100:3100"
    env_file:
      - .env
    networks:
      - reverse_proxy

  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    env_file:
      - .env
    ports:
      - 8123:8123
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', '127.0.0.1:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
    networks:
      - reverse_proxy

  grafana:
    image: grafana/grafana-oss:10.2.2
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - qryn
    networks:
      - reverse_proxy

  questdb:
     image: questdb/questdb
     container_name: questdb
     restart: always
     volumes:
       - ./questdb:/var/lib/questdb
     networks:
         - reverse_proxy
     ports:
       - "8812:8812"
       - "9000:9000"
       - "9009:9009"
       - "9003:9003"
